seed: 0
num_epochs: 10
head_dim: 128
dictionary_size: 4096
sparsity: 32
num_layers: 32
num_heads: 8
batch_size: 64
lm_batch_size: 16
dataset_size: 1801350
buffer_mult: 384
lr: 0.0001
beta1: 0.9
beta2: 0.99
device: "cuda:0"