seed: 7
num_epochs: 1
head_dim: 128
dictionary_size: 4096
sparsity: 32
num_layers: 32
num_heads: 8
batch_size: 8
lm_batch_size: 8
dataset_size: 10000 #1801350
buffer_mult: 48
lr: 0.0001
beta1: 0.9
beta2: 0.99
device: "cuda:0"